import { Country, Company, Region, Store, Employee, ShiftType, Shift, Schedule, HandoverRecord, Role } from '../types'

export const initialCountries: Country[] = [
  { id: 'ct1', code: 'CN', name: '中国', isActive: true, createdAt: '2024-01-01' },
  { id: 'ct2', code: 'VN', name: '越南', isActive: true, createdAt: '2024-01-01' },
]

export const initialRoles: Role[] = [
  { id: 'role1', name: '督导', companyId: 'c1', dataScope: 'region', menuKeys: ['/pc', '/pc/stores', '/pc/regions', '/pc/employees', '/pc/shift-types', '/pc/handover', '/pc/permissions'], buttonCodes: ['region:add', 'region:edit', 'region:delete', 'store:add', 'store:edit', 'store:delete', 'employee:add', 'employee:edit', 'employee:delete', 'shiftType:add', 'shiftType:edit', 'shiftType:delete', 'handover:view', 'handover:export', 'mobile:createShift', 'mobile:scheduling', 'mobile:transfer', 'mobile:approveTransfer', 'mobile:handover', 'mobile:approveHandover', 'mobile:storeSwitch'], isActive: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'role2', name: '稽核专员', companyId: 'c1', dataScope: 'company', menuKeys: ['/pc', '/pc/stores', '/pc/regions', '/pc/employees', '/pc/shift-types', '/pc/handover', '/pc/permissions'], buttonCodes: ['region:add', 'region:edit', 'region:delete', 'store:add', 'store:edit', 'store:delete', 'employee:add', 'employee:edit', 'employee:delete', 'shiftType:add', 'shiftType:edit', 'shiftType:delete', 'handover:view', 'handover:export'], isActive: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'role3', name: '店长', companyId: 'c1', dataScope: 'store', menuKeys: ['/pc', '/pc/handover'], buttonCodes: ['handover:view', 'mobile:createShift', 'mobile:scheduling', 'mobile:transfer', 'mobile:approveTransfer', 'mobile:handover', 'mobile:approveHandover', 'mobile:recruit'], isActive: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'role4', name: '全职店员', companyId: 'c1', dataScope: 'self', menuKeys: ['/pc'], buttonCodes: [], isActive: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'role5', name: '管培生', companyId: 'c1', dataScope: 'self', menuKeys: ['/pc'], buttonCodes: [], isActive: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'role6', name: '兼职店员', companyId: 'c1', dataScope: 'self', menuKeys: ['/pc'], buttonCodes: [], isActive: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'role7', name: '督导', companyId: 'c2', dataScope: 'region', menuKeys: ['/pc', '/pc/stores', '/pc/regions', '/pc/employees', '/pc/shift-types', '/pc/handover', '/pc/permissions'], buttonCodes: ['region:add', 'region:edit', 'region:delete', 'store:add', 'store:edit', 'store:delete', 'employee:add', 'employee:edit', 'employee:delete', 'shiftType:add', 'shiftType:edit', 'shiftType:delete', 'handover:view', 'handover:export', 'mobile:createShift', 'mobile:scheduling', 'mobile:transfer', 'mobile:approveTransfer', 'mobile:handover', 'mobile:approveHandover', 'mobile:storeSwitch'], isActive: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'role8', name: '店长', companyId: 'c2', dataScope: 'store', menuKeys: ['/pc', '/pc/handover'], buttonCodes: ['handover:view', 'mobile:createShift', 'mobile:scheduling', 'mobile:transfer', 'mobile:approveTransfer', 'mobile:handover', 'mobile:approveHandover', 'mobile:recruit'], isActive: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
]

export const initialCompanies: Company[] = [
  { id: 'c1', countryId: 'ct1', companyNo: 'OHMEE-CN', companyName: 'Ohmee 中国', isActive: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'c2', countryId: 'ct2', companyNo: 'OHMEE-VN', companyName: 'Ohmee 越南', isActive: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
]

export const initialRegions: Region[] = [
  { id: 'r1', name: '华东区', companyId: 'c1', createdAt: '2024-01-01' },
  { id: 'r2', name: '华南区', companyId: 'c1', createdAt: '2024-01-01' },
  { id: 'r3', name: '华北区', companyId: 'c1', createdAt: '2024-01-01' },
]

export const initialStores: Store[] = [
  {
    id: 's1',
    storeNo: 'SH001',
    storeName: '上海南京路店',
    address: '上海市黄浦区南京东路100号',
    lat: 31.2362,
    lng: 121.4793,
    status: '营业中',
    type: '直营店',
    regionId: 'r1',
    companyId: 'c1',
    supervisorId: 'e1',
    managerId: 'e3',
    isActive: true,
    createdAt: '2023-03-15',
    updatedAt: '2024-01-10',
  },
  {
    id: 's2',
    storeNo: 'SH002',
    storeName: '上海人民广场店',
    address: '上海市黄浦区人民大道200号',
    lat: 31.2304,
    lng: 121.4737,
    status: '营业中',
    type: '直营店',
    regionId: 'r1',
    companyId: 'c1',
    supervisorId: 'e1',
    managerId: 'e4',
    isActive: true,
    createdAt: '2023-06-20',
    updatedAt: '2024-01-10',
  },
  {
    id: 's3',
    storeNo: 'GZ001',
    storeName: '广州天河店',
    address: '广州市天河区天河路385号',
    lat: 23.1291,
    lng: 113.2644,
    status: '营业中',
    type: '托管店',
    regionId: 'r2',
    companyId: 'c1',
    supervisorId: 'e2',
    managerId: 'e5',
    isActive: true,
    createdAt: '2023-09-01',
    updatedAt: '2024-01-10',
  },
  {
    id: 's4',
    storeNo: 'BJ001',
    storeName: '北京王府井店',
    address: '北京市东城区王府井大街88号',
    lat: 39.9154,
    lng: 116.4072,
    status: '建设中',
    type: '特许加盟店',
    regionId: 'r3',
    companyId: 'c1',
    supervisorId: 'e2',
    managerId: '',
    isActive: true,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
]

export const initialEmployees: Employee[] = [
  {
    id: 'e1',
    empNo: 'EMP001',
    name: '张伟',
    gender: '男',
    age: 35,
    role: '督导',
    roleId: 'role1',
    joinDate: '2020-03-01',
    storeId: 's1',
    regionId: 'r1',
    companyId: 'c1',
    assignedRegionIds: ['r1'],
    isActive: true,
    password: '123456',
  },
  {
    id: 'e2',
    empNo: 'EMP002',
    name: '李娜',
    gender: '女',
    age: 32,
    role: '督导',
    roleId: 'role1',
    joinDate: '2020-06-15',
    storeId: 's3',
    regionId: 'r2',
    companyId: 'c1',
    assignedRegionIds: ['r2'],
    isActive: true,
    password: '123456',
  },
  {
    id: 'e3',
    empNo: 'EMP003',
    name: '王强',
    gender: '男',
    age: 28,
    role: '店长',
    joinDate: '2021-01-10',
    storeId: 's1',
    regionId: 'r1',
    companyId: 'c1',
    isActive: true,
    password: '123456',
  },
  {
    id: 'e4',
    empNo: 'EMP004',
    name: '赵敏',
    gender: '女',
    age: 26,
    role: '店长',
    joinDate: '2021-05-20',
    storeId: 's2',
    regionId: 'r1',
    companyId: 'c1',
    isActive: true,
    password: '123456',
  },
  {
    id: 'e5',
    empNo: 'EMP005',
    name: '陈刚',
    gender: '男',
    age: 30,
    role: '店长',
    joinDate: '2021-09-01',
    storeId: 's3',
    regionId: 'r2',
    companyId: 'c1',
    isActive: true,
    password: '123456',
  },
  {
    id: 'e6',
    empNo: 'EMP006',
    name: '刘洋',
    gender: '男',
    age: 23,
    role: '全职店员',
    joinDate: '2022-03-15',
    storeId: 's1',
    regionId: 'r1',
    companyId: 'c1',
    isActive: true,
    password: '123456',
  },
  {
    id: 'e7',
    empNo: 'EMP007',
    name: '周晓',
    gender: '女',
    age: 22,
    role: '全职店员',
    joinDate: '2022-07-01',
    storeId: 's1',
    regionId: 'r1',
    companyId: 'c1',
    isActive: true,
    password: '123456',
  },
  {
    id: 'e8',
    empNo: 'EMP008',
    name: '吴磊',
    gender: '男',
    age: 20,
    role: '兼职店员',
    joinDate: '2023-01-10',
    storeId: 's2',
    regionId: 'r1',
    companyId: 'c1',
    isActive: true,
    password: '123456',
  },
  {
    id: 'e9',
    empNo: 'EMP009',
    name: '孙艳',
    gender: '女',
    age: 24,
    role: '管培生',
    joinDate: '2023-06-01',
    storeId: 's1',
    regionId: 'r1',
    companyId: 'c1',
    isActive: true,
    password: '123456',
  },
  {
    id: 'e10',
    empNo: 'EMP010',
    name: '徐浩',
    gender: '男',
    age: 25,
    role: '稽核专员',
    roleId: 'role2',
    joinDate: '2022-11-01',
    storeId: 's2',
    regionId: 'r1',
    companyId: 'c1',
    isActive: true,
    password: '123456',
  },
]

export const initialShiftTypes: ShiftType[] = [
  {
    id: 'st1',
    typeNo: 'ST001',
    typeName: '早班',
    companyId: 'c1',
    updatedBy: '系统管理员',
    updatedAt: '2024-01-01',
    isActive: true,
  },
  {
    id: 'st2',
    typeNo: 'ST002',
    typeName: '中班',
    companyId: 'c1',
    updatedBy: '系统管理员',
    updatedAt: '2024-01-01',
    isActive: true,
  },
  {
    id: 'st3',
    typeNo: 'ST003',
    typeName: '晚班',
    companyId: 'c1',
    updatedBy: '系统管理员',
    updatedAt: '2024-01-01',
    isActive: true,
  },
  {
    id: 'st4',
    typeNo: 'ST004',
    typeName: '大夜班',
    companyId: 'c1',
    updatedBy: '系统管理员',
    updatedAt: '2024-01-01',
    isActive: true,
  },
]

export const initialShifts: Shift[] = [
  {
    id: 'sh1',
    shiftNo: 'SH001',
    shiftName: '早班 07:00-15:00',
    startTime: '07:00',
    endTime: '15:00',
    typeId: 'st1',
    storeId: 's1',
    createdBy: 'e3',
    isActive: true,
    createdAt: '2024-01-15',
  },
  {
    id: 'sh2',
    shiftNo: 'SH002',
    shiftName: '中班 15:00-23:00',
    startTime: '15:00',
    endTime: '23:00',
    typeId: 'st2',
    storeId: 's1',
    createdBy: 'e3',
    isActive: true,
    createdAt: '2024-01-15',
  },
  {
    id: 'sh3',
    shiftNo: 'SH003',
    shiftName: '早班 07:00-15:00',
    startTime: '07:00',
    endTime: '15:00',
    typeId: 'st1',
    storeId: 's2',
    createdBy: 'e4',
    isActive: true,
    createdAt: '2024-01-15',
  },
]

export const initialSchedules: Schedule[] = [
  {
    id: 'sc1',
    empId: 'e6',
    shiftId: 'sh1',
    startDate: '2026-02-01',
    endDate: '2026-02-28',
    storeId: 's1',
    createdBy: 'e3',
    createdAt: '2026-01-28',
  },
  {
    id: 'sc2',
    empId: 'e7',
    shiftId: 'sh2',
    startDate: '2026-02-01',
    endDate: '2026-02-28',
    storeId: 's1',
    createdBy: 'e3',
    createdAt: '2026-01-28',
  },
  {
    id: 'sc3',
    empId: 'e9',
    shiftId: 'sh1',
    startDate: '2026-02-01',
    endDate: '2026-02-28',
    storeId: 's1',
    createdBy: 'e3',
    createdAt: '2026-01-28',
  },
]

export const initialHandovers: HandoverRecord[] = [
  {
    id: 'hv1',
    storeId: 's1',
    companyId: 'c1',
    handoverEmpId: 'e6',
    handoverEmpName: '刘洋',
    handoverRole: '全职店员',
    handoverShiftId: 'sh1',
    handoverShiftName: '早班 07:00-15:00',
    receivers: [
      { empId: 'e7', empName: '周晓', role: '全职店员', shiftName: '中班 15:00-23:00' },
    ],
    cashDifference: false,
    hasInventory: true,
    inventoryDiff: false,
    hasRestocked: true,
    status: '已确认',
    reviewedBy: 'e3',
    createdAt: '2026-02-28 15:02:00',
    updatedAt: '2026-02-28 15:10:00',
  },
  {
    id: 'hv2',
    storeId: 's1',
    companyId: 'c1',
    handoverEmpId: 'e7',
    handoverEmpName: '周晓',
    handoverRole: '全职店员',
    handoverShiftId: 'sh2',
    handoverShiftName: '中班 15:00-23:00',
    receivers: [
      { empId: 'e9', empName: '孙艳', role: '管培生', shiftName: '早班 07:00-15:00' },
    ],
    cashDifference: true,
    cashDiffAmount: 50,
    cashDiffReason: '收银台找零操作失误，差50元',
    hasInventory: true,
    inventoryDiff: true,
    inventoryDiffNote: '矿泉水少4瓶，可能被误拿',
    hasRestocked: false,
    status: '待审核',
    createdAt: '2026-03-01 23:05:00',
    updatedAt: '2026-03-01 23:05:00',
  },
]
